# Generated by Django 5.1.6 on 2025-03-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_marketdata_stock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('AAPL', 'Apple'), ('AMZN', 'Amazon'), ('GOOG', 'Google'), ('TSLA', 'Tesla')], default='AAPL', max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'date'], name='marketdata__company_e5fc7f_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.AlterField(
            model_name='marketprediction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.stockdata'),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.stockdata'),
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
    ]
