# Generated by Django 5.1.6 on 2025-03-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
