# Generated by Django 5.1.6 on 2025-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0003_stockdata_alter_marketprediction_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentimentanalysis",
            name="tweet_text",
        ),
        migrations.AddField(
            model_name="sentimentanalysis",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
