# Generated by Django 5.1.6 on 2025-03-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketdata", "0004_remove_sentimentanalysis_tweet_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentimentanalysis",
            name="article_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
